name: Check regularity
on:
  push:
      branches:
        - master
        - main
#   schedule:
#     - cron: 0 * * * *

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - run: pacman -Sy wget git python python-pip --noconfirm
      - run: wget https://bootstrap.pypa.io/get-pip.py
      - run: python get-pip.py
      - run: pip install requests
      - run: pacman-key --init
      - run: bash devready.sh
      - run: pacman -Sy
      - run: ./bin/comparepkgs
