name: Check regularity
on:
  schedule:
    - cron: "*/60 * * * *"


jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - run: pacman -Sy wget git --noconfirm
      - run: pacman-key --init
      - run: bash devready.sh
      - run: ./bin/comparepkgs